# Add Homebrew `/usr/local/bin` and User `~/bin` to the `$PATH`
PATH=/usr/local/bin:$PATH
PATH=$HOME/bin:$PATH
export PATH

# Load the shell dotfiles, and then some:
# * ~/.path can be used to extend `$PATH`.
# * ~/.extra can be used for other settings you don’t want to commit.
for file in ~/.{path,bash_prompt,exports,aliases,functions,extra}; do
  [ -r "$file" ] && source "$file"
done
unset file

    alias ls='ls -G'
    alias cleanupDS="find . -type f -name '*.DS_Store' -ls -delete"
#   finderShowHidden:   Show hidden files in Finder
#   finderHideHidden:   Hide hidden files in Finder
#   -------------------------------------------------------------------
    alias finderShowHidden='defaults write com.apple.finder ShowAllFiles TRUE'
    alias finderHideHidden='defaults write com.apple.finder ShowAllFiles FALSE'
#   atajos para virtualenv
    alias startEnv='virtualenv --no-site-packages env'
    alias activate='source env/bin/activate'
#   atajos para pip
    alias pipInstall='pip install -r requirements.txt'
#   django atajos
    alias dj.r='python manage.py runserver 0.0.0.0'
    alias dj.mkm='python manage.py makemigrations'
    alias dj.m='python manage.py migrate'
#   directorios
    alias ..='cd ..'
    alias ...='cd ../../'
    alias .3='cd ../../../'
    alias .4='cd ../../../../'
    alias .5='cd ../../../../../'
    alias .6='cd ../../../../../../'
    alias c='clear'
#   goToProjects
    alias gotoDecipherWeb='cd ~/Projects/decipherweb/'
    alias gotoMonitorServer='cd ~/Projects/monitor-server/'
#   vim
    alias vi='vim'
    alias svi='sudo vi'
    alias edit='vim'

#   ALIAS FOR PROJECTS
#   decipherweb
    alias decipherUgly='grunt uglify-files --verbose --gruntfile config/grunt.conf.js'
    alias decipherWork='python manage.py rqworker high default low --worker-class home.asynchandler.CustomWorker'

# Add environment variable COCOS_CONSOLE_ROOT for cocos2d-x
export COCOS_CONSOLE_ROOT=/Applications/Cocos/Cocos2d-x/cocos2d-x-3.10/tools/cocos2d-console/bin
export PATH=$COCOS_CONSOLE_ROOT:$PATH

# Add environment variable COCOS_X_ROOT for cocos2d-x
export COCOS_X_ROOT=/Applications/Cocos/Cocos2d-x
export PATH=$COCOS_X_ROOT:$PATH

# Add environment variable COCOS_TEMPLATES_ROOT for cocos2d-x
export COCOS_TEMPLATES_ROOT=/Applications/Cocos/Cocos2d-x/cocos2d-x-3.10/templates
export PATH=$COCOS_TEMPLATES_ROOT:$PATH

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

